version: "3"

output: prefixed

silent: true

dotenv: [".env"]

tasks:
  test:
    desc: Test all days
    cmds:
      - go test ./...

  test:coverage:
    desc: Generate test coverage report
    cmds:
      - go test ./... -coverprofile=cov.out
      - defer: rm cov.out
      - go tool cover -html=cov.out

  new:
    desc: Prepare next day challenge
    cmds:
      - |
        day={{(split " " .CLI_ARGS)._1}}
        if [[ ${#day} -lt 2 ]] ; then day="00${day}"; day="${day: -2}"; fi
        DIR={{(split " " .CLI_ARGS)._0}}/day${day}
        if [ -d ${DIR} ]; then echo "${DIR} directory exists."; exit 1; fi
        echo "creating $DIR"
        mkdir -p $DIR
        cp -R template/ ${DIR}/
        curl --silent --cookie "session=${ADVENT_OF_CODE_COOKIE}" https://adventofcode.com/{{(split " " .CLI_ARGS)._0}}/day/{{(split " " .CLI_ARGS)._1}}/input -o ${DIR}/input.txt
        echo "input.txt downloaded"
