version: "3"

output: prefixed

silent: true

dotenv: [".env"]

tasks:
  prepare:
    desc: Download dependencies and prepare dev env
    cmds:
      - go mod download
      - go mod tidy
      - go mod vendor

  test:
    desc: Test all days
    cmds:
      - go test ./...

  test:coverage:
    desc: Generate test coverage report
    cmds:
      - go test ./... -coverprofile=cov.out
      - defer: rm cov.out
      - go tool cover -html=cov.out

  new:
    desc: Prepare next day challenge
    cmds:
      - |
        day={{index (splitArgs .CLI_ARGS) 1}}
        if [[ ${#day} -lt 2 ]] ; then day="00${day}"; day="${day: -2}"; fi
        DIR={{index (splitArgs .CLI_ARGS) 0}}/day${day}
        if [ -d ${DIR} ]; then echo "${DIR} directory exists."; exit 1; fi
        echo "creating $DIR"
        mkdir -p $DIR
        cp -R template/ ${DIR}/
        curl --silent --cookie "session=${ADVENT_OF_CODE_COOKIE}" https://adventofcode.com/{{index (splitArgs .CLI_ARGS) 0}}/day/{{index (splitArgs .CLI_ARGS) 1}}/input -o ${DIR}/input.txt
        echo "input.txt downloaded"
